config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "memos#index"
  resources :memos do
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :memo
  belongs_to :user

  validates :comment, presence: true
end

app/models/memo.rb
class Memo < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :comments
  
  validates :title, :impression, :date, :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: "半角英数混合で６文字以上で入力してください"

  has_many :memos
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to memo_path(comment.memo.id)
  end

  def destroy
    @memo = Memo.find(params[:memo_id])
    comment = @memo.comments.find(params[:id])
    if current_user.id == comment.user.id
      comment.destroy
      redirect_back(fallback_location: root_path)
    else
      render "memos/show"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:comment).merge(user_id: current_user.id, memo_id: params[:memo_id])
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_memo, only: [:edit, :show, :update]
  
  def index
    @memos = Memo.all.order("created_at DESC")
  end

  def new
    @memo = Memo.new
  end

  def create
    @memo = Memo.new(memo_params)
    if @memo.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @memo.comments.includes(:user)
  end

  def edit
    unless current_user.id == @memo.user_id
      redirect_to root_path
    end
  end

  def update
    if @memo.update(memo_params)
      redirect_to memo_path(@memo.id)
    else
      render :edit
    end
  end

  def destroy
    memo = Memo.find(params[:id])
    if current_user.id == memo.user_id
      memo.destroy
      redirect_to root_path
    end
  end

  private
  def memo_params
    params.require(:memo).permit(:title, :date, :impression, :image).merge(user_id: current_user.id)
  end

  def set_memo
    @memo = Memo.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @nickname = current_user.nickname
    @memos = current_user.memos.order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>CAFE LOG</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <%= javascript_pack_tag 'application' %>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/memos/edit.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('cafelog-logo.png' , class: "items-sell-header-logo", size: '185x80'), "/" %>
  </header>
  <div class="items-sell-header-image">
    <%= image_tag "cafelog-edit-top.png", class: "items-sell-header-image" %>
  </div>
  <div class="items-sell-main">
    <h2 class="items-sell-title">
      入力項目
    </h2>
    <%= form_with model: @memo, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 商品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        画像
      </div>
      <div class="click-upload">
        <p>
          画像をアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /商品画像 %>

    <%# メモの内容 %>
    <div class="new-items">
      <div class="weight-bold-text">
        タイトル
      </div>
      <%= f.text_area :title, class:"items-text", id:"item-name", placeholder:"タイトル（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          日付
        </div>
        <%= f.date_field :date, class:"form-control" %>
      </div>
      <div class="items-explain">
        <div class="weight-bold-text">
          感想
        </div>
        <%= f.text_area :impression, class:"items-text", id:"item-info", placeholder:"コーヒーの感想（1,000文字まで）（味、香り、飲み方など）例）コーヒーショップで購入したブレンドコーヒーです。ほんのりナッツの香りがします。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /メモの内容 %>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <div class="submit">
        <%= f.submit "変更する" ,class:"sell-btn" %>
      </div>
      <div class="back">
        <%=link_to 'もどる', memo_path(@memo.id), class:"back-btn" %>
      </div>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <p class="inc">
      ©︎CAFE LOG
    </p>
  </footer>
</div>

app/views/memos/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 画面上部 %>
  <div class='title-contents'>
    <%= link_to image_tag("cafelog.png", class:"main-pict"), "#" %>
  </div>
  <%# /画面上部 %>

  <%# CAFE LOGの使い方 %>
  <div class='feature-contents'>
    <h2 class='title'>
      CAFE LOGの使い方
    </h2>
    <ul class='feature-lists'>
      <li class='list'>
        <%= image_tag "cafelog-post.png", class:"list-pict" %>
        <p class='feature-list-description'>
          飲んだコーヒーの感想を<br>
          投稿しよう
        </p>
      </li>
      <li class='list'>
        <%= image_tag "cafelog-comment.png", class:"list-pict" %>
        <p class='feature-list-description'>
          投稿者と交流しよう
        </p>
      </li>
      <li class='list'>
        <%= image_tag "cafelog-info.png", class:"list-pict" %>
        <p class='feature-list-description'>
          コーヒー情報を活用しよう
        </p>
      </li>
    </ul>
  </div>
  <%# /CAFE LOGの使い方 %>

<%# コーヒー情報一覧 %>
  <div class='item-contents'>
    <h2 class='title'>Topics</h2>
    <ul class='item-lists'>
      <li class='list'>
        <%= link_to "#" do %>
        <div class='item-img-content'>
          <%= image_tag "cafelog-brand.png", class: "item-img" %>

        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= "タイトル" %>
          </h3>
          <div class='item-price'>
            <span><%= "ジャンル" %></span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
          <div class='item-price'>
            <span><%= "日付" %></span>
          </div>
        </div>
        <% end %>
      </li>
      
      <li class='list'>
        <%= link_to '#' do %>
        <%= image_tag "cafelog-info-sample.png", class: "item-img" %>
        <div class='item-info'>
          <h3 class='item-name'>
            コーヒーを選ぶときの<br>
            参考にしよう
          </h3>
           <div class='item-price'>
            <span><%= "ジャンル" %></span>
          </div>
          <div class='item-price'>
            <span><%= "日付" %></span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
    </ul>
  </div>
  <%# /コーヒー情報一覧 %>

  <%# コーヒーメモ一覧 %>
  <div class='item-contents'>
    <h2 class='title'>Time Line</h2>
    <ul class='item-lists'>
      <% @memos.each do |memo| %>
        <li class='list'>
          <%= link_to memo_path(memo.id) do %>
            <div class='item-img-content'>
              <%= image_tag memo.image, class: 'item-img' if memo.image.attached? %>
            </div>
            <div class='item-info'>
              <h3 class='item-name'>
                <%= memo.title %>
              </h3>
              <div class='item-price'>
                <span><%= memo.date %></span>
                <div class='star-btn'>
                  <%= image_tag "star.png", class:"star-icon" %>
                  <span class='star-count'>0</span>
                </div>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>

      <% if @memos.empty? %>
        <li class='list'>
          <%= link_to '#' do %>
          <%= image_tag "cafelog-timeline-sample.png", class: "item-img" %>
          <div class='item-info'>
            <h3 class='item-name'>
              コーヒーメモを投稿しよう
            </h3>
            <div class='item-price'>
              <span>2023年1月1日</span>
              <div class='star-btn'>
                <%= image_tag "star.png", class:"star-icon" %>
                <span class='star-count'>0</span>
              </div>
            </div>
          </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
  <%# /コーヒーメモ一覧 %>
</div>
<%= link_to(new_memo_path, class: 'post-btn') do %>
  <%= image_tag 'cafelog-post-btn.png' , size: '185x50' ,class: "post-btn-icon" %>
<% end %>
<%= render "shared/footer" %>

app/views/memos/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('cafelog-logo.png' , class: "items-sell-header-logo", size: '185x80'), "/" %>
  </header>
  <div class="items-sell-header-image">
    <%= image_tag "cafelog-post-top.png", class: "items-sell-header-image" %>
  </div>
  <div class="items-sell-main">
    <h2 class="items-sell-title">
      入力項目
    </h2>
    <%= form_with model: @memo, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 商品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        画像
      </div>
      <div class="click-upload">
        <p>
          画像をアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /商品画像 %>

    <%# メモの内容 %>
    <div class="new-items">
      <div class="weight-bold-text">
        タイトル
      </div>
      <%= f.text_area :title, class:"items-text", id:"item-name", placeholder:"タイトル（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          日付
        </div>
        <%= f.date_field :date, class:"form-control" %>
      </div>
      <div class="items-explain">
        <div class="weight-bold-text">
          感想
        </div>
        <%= f.text_area :impression, class:"items-text", id:"item-info", placeholder:"コーヒーの感想（1,000文字まで）（味、香り、飲み方など）例）コーヒーショップで購入したブレンドコーヒーです。ほんのりナッツの香りがします。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /メモの内容 %>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <%# link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎CAFE LOG
    </p>
  </footer>
</div>

app/views/memos/show.html.erb
<%= render "shared/header" %>

<div class="item-show">
  <% if user_signed_in? && current_user.id == @memo.user_id %>
    <div class="item-btn">
      <%= link_to "編集", edit_memo_path(@memo.id), method: :get, class: "item-edit-btn" %>
      <%= link_to "削除", memo_path(@memo.id), method: :delete, class:"item-destroy" %>
    </div>
  <% end %>

  <div class="item-box">
    <h2 class="name">
      <%= @memo.user.nickname %>
    </h2>

    <h2 class="name">
      <%= @memo.title %>
    </h2>

    <h2 class="date">
      <%= @memo.date %>
    </h2>

    <div class="item-img-content">
      <%= image_tag @memo.image ,class:"item-box-img" %>
    </div>

    <div class="item-explain-box">
      <span><%= @memo.impression %></span>
    </div>
    
    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span>お気に入り 0</span>
      </div>

      <div class="report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切な画像の通報</span>
      </div>
    </div>
  </div>

  <div class="comment-box">
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% @comments.each do |comment| %>
        <div class="comments-items">
          <div class="comments-item-left">
            <div class="comments-date">
              <%= l comment.created_at %>
            </div>
            <div class="comments-conntent">
              <p>
                <%= comment.user.nickname %>：
                <%= comment.comment %>
              </p>
            </div>
          </div>
          <div class="comments-item-right">
            <% if user_signed_in? && current_user.id == comment.user_id %>
              <div> 
                <%= link_to '削除', memo_comment_path(@memo, comment),class:"delete-btn", method: :delete %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="container">
      <% if user_signed_in? %>
        <%= form_with(model: [@memo, @comment], local: true) do |f| %>
          <%= f.text_area :comment, :class => 'comment-text', placeholder: "コメントする", rows: "2" %>
          <%= f.submit "コメントする", :class => 'comment-btn' %>
        <% end %>
      <% else %>
        <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
      <% end %>
      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p>
    </div>
    <div class="back">
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  </div>
  
  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の投稿
    </a>
    <a href="#" class="change-item-btn">
      次の投稿 ＞
    </a>
  </div>
  
</div>

<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  
  <div class='store-btn'>
    
  </div>
</div>
<%# /下部広告部分 %>

<div class='footer'>
  <div class='footer-contents'>
    <div class='cafelog-details'>
      <h2 class='footer-content-head'>CAFE LOGについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'CAFE LOG利用規約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='cafelog-details'>
      <h2 class='footer-content-head'>CAFE LOGについて</h2>
      <ul>
        <li><%= link_to 'CAFE LOGガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <p>© CAFE LOG</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='nav'>
    <ul class='lists-left'>
      <%= link_to image_tag("cafelog-logo.png", class:"logo", size: '185x80'), "/" %>
    </ul>
    <ul class='lists-right'>
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, user_path(id: current_user), class: "user-nickname" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>CAFE LOG利用規約</p>
  </div>
  <p class='copyright'>© CAFE LOG</p>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("cafelog-logo.png", class:"logo", size: '185x80'), "/" %>
</header>

app/views/users/show.html.erb
<%= render "shared/header" %>
<div class='main'>
  <div class='item-contents'>
  <p class="user-name"><%= @nickname %>さんの投稿一覧</p>
    <ul class='item-lists'>
      <% @memos.each do |memo| %>
        <li class='list'>
          <%= link_to memo_path(memo.id) do %>
            <div class='item-img-content'>
              <%= image_tag memo.image, class: 'item-img' if memo.image.attached? %>
            </div>
            <div class='item-info'>
              <h3 class='item-name'>
                <%= memo.title %>
              </h3>
              <div class='item-date'>
                <span><%= memo.date %></span>
                <div class='star-btn'>
                  <%= image_tag "star.png", class:"star-icon" %>
                  <span class='star-count'>0</span>
                </div>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
    <div class="back">
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  </div>
</div>